name: 'Continuous Integration'
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: 'Check out repository code'
          uses: actions/checkout@v4

        - name: 'Setup Go environment'
          uses: actions/setup-go@v5
          with:
            go-version: 'stable'
        - run: go run main.go