name: 'Continuous Delivery'
on:
    push:
        branches:
            - main

jobs:
    deliver:
        runs-on: ubuntu-latest
        steps:
        - name: 'Check out repository code'
          uses: actions/checkout@v4

        - name: Simulando Continuous Delivery
          uses: actions/upload-artifact@v4
          with:
            name: omni-cli
            path: omni-cli

    deploy:
        runs-on: ubuntu-latest
        needs: deliver
        steps:
          - uses: actions/download-artifact@v4
            with:
              name: omni-cli
          - name: Display structure of downloaded files
            run: ls -R

    
    docker:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/omni-cli:latest