name: 'Continuous Integration'
on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: 'Check out repository code'
            uses: actions/checkout@v4

          - name: 'Set up Go environment'
            uses: actions/setup-go@v5
            with:
              go-version: 'stable'

          - name: 'Run tests'
            run: go test ./... -v

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
        - name: 'Check out repository code'
          uses: actions/checkout@v4

        - name: 'Setup Go environment'
          uses: actions/setup-go@v5
          with:
            go-version: 'stable'
        - run: go run main.go
