name: 'Continuous Delivery'
on:
    push:
        branches:
            - main

jobs:
    deliver:
        runs-on: ubuntu-latest
        steps:
        - name: 'Check out repository code'
          uses: actions/checkout@v4

        - name: Simulando Continuous Delivery
          uses: actions/upload-artifact@v4
          with:
            name: omni-cli
            path: omni-cli

    deploy:
        runs-on: ubuntu-latest
        needs: deliver
        steps:
          - uses: actions/download-artifact@v4
            with:
              name: omni-cli
          - name: Display structure of downloaded files
            run: ls -R