name: 'Continuous Integration'
on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go-version: ['1.20', '1.21', '1.23.x', 'stable']

        steps:
          - name: 'Check out repository code'
            uses: actions/checkout@v4

          - name: 'Set up Go environment'
            uses: actions/setup-go@v5
            with:
              go-version: ${{ matrix.go-version }}

          - name: Install dependencies
            run: go get .

          - name: 'Run tests'
            run: go test ./... -v -json > TestResults-${{ matrix.go-version }}.json

          - name: Upload Go test results
            uses: actions/upload-artifact@v4
            with:
              name: Go-results-${{ matrix.go-version }}
              path: TestResults-${{ matrix.go-version }}.json

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
        - name: 'Check out repository code'
          uses: actions/checkout@v4

        - name: 'Setup Go environment'
          uses: actions/setup-go@v5
          with:
            go-version: 'stable'
        - run: go run main.go
